config/routes.rb
SoulControlBack::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :areas

  resources :countries

  resources :locations

  resources :venue_roles

  resources :venue_users

  resources :venues

  resources :statuses

  resources :tours

  resources :events

  resources :event_user_statuses

  resources :artists

  resources :roles

  resources :users

  resources :companies

  get "soulcontrol" => "soulcontrol#index"

  devise_scope :user do

    authenticated :user do
      root 'soulcontrol#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

  end

  

end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :artist_users
  has_many :users, through: :artist_users
  has_many :events
end

app/models/artist_user.rb
class ArtistUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :artist
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :locations
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_user_statuses
  has_many :users, through: :event_user_statuses
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :companies
  has_many :venues
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles
  has_many :users, through: :user_roles
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :events
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :user_roles
  has_many :roles, through: :user_roles

  has_many :artist_users
  has_many :artists, through: :artist_users

  has_many :event_user_statuses
  has_many :events, through: :event_user_statuses

  has_many :venue_users
  has_many :venues, through: :venue_users

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :venue_users
  has_many :users, through: :venue_users
  has_many :events
end

app/models/venue_role.rb
class VenueRole < ActiveRecord::Base
  has_many :venue_users
end

app/models/venue_user.rb
class VenueUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue
end

app/controllers/venue_users_controller.rb
class VenueUsersController < ApplicationController
  before_action :set_venue_user, only: [:show, :edit, :update, :destroy]

  # GET /venue_users
  # GET /venue_users.json
  def index
    @venue_users = VenueUser.all
  end

  # GET /venue_users/1
  # GET /venue_users/1.json
  def show
    @venue_user = VenueUser.find(params[:id])
  end

  # GET /venue_users/new
  def new
    @venue_user = VenueUser.new
  end

  # GET /venue_users/1/edit
  def edit
  end

  # POST /venue_users
  # POST /venue_users.json
  def create
    @venue_user = VenueUser.new(venue_user_params)

    respond_to do |format|
      if @venue_user.save
        format.html { redirect_to @venue_user, notice: 'Venue user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @venue_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @venue_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venue_users/1
  # PATCH/PUT /venue_users/1.json
  def update
    respond_to do |format|
      if @venue_user.update(venue_user_params)
        format.html { redirect_to @venue_user, notice: 'Venue user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @venue_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venue_users/1
  # DELETE /venue_users/1.json
  def destroy
    @venue_user.destroy
    respond_to do |format|
      format.html { redirect_to venue_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue_user
      @venue_user = VenueUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_user_params
      params[:venue_user].permit(:venuer_role_id, :user_id, :venue_id)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venue_users_helper.rb
module VenueUsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venue_users/_form.html.erb
<%= form_for(@venue_user) do |f| %>
  <% if @venue_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue_user.errors.count, "error") %> prohibited this venue_user from being saved:</h2>

      <ul>
      <% @venue_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venue_users/edit.html.erb
<h1>Editing venue_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue_user %> |
<%= link_to 'Back', venue_users_path %>

app/views/venue_users/index.html.erb
<h1>Listing venue_users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @venue_users.each do |venue_user| %>
      <tr>
        <td><%= link_to 'Show', venue_user %></td>
        <td><%= link_to 'Edit', edit_venue_user_path(venue_user) %></td>
        <td><%= link_to 'Destroy', venue_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue user', new_venue_user_path %>

app/views/venue_users/new.html.erb
<h1>New venue_user</h1>

<%= render 'form' %>

<%= link_to 'Back', venue_users_path %>

app/views/venue_users/show.html.erb
<%= link_to 'Edit', edit_venue_user_path(@venue_user) %> |
<%= link_to 'Back', venue_users_path %>