config/routes.rb
SoulControlBack::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :areas

  resources :countries

  resources :locations

  resources :venue_roles

  resources :venue_users

  resources :venues

  resources :statuses

  resources :tours

  resources :events

  resources :event_user_statuses

  resources :artists

  resources :roles

  resources :users

  resources :companies

  get "soulcontrol" => "soulcontrol#index"

  devise_scope :user do

    authenticated :user do
      root 'soulcontrol#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

  end

  

end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :artist_users
  has_many :users, through: :artist_users
  has_many :events
end

app/models/artist_user.rb
class ArtistUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :artist
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :locations
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_user_statuses
  has_many :users, through: :event_user_statuses
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :companies
  has_many :venues
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles
  has_many :users, through: :user_roles
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :events
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :user_roles
  has_many :roles, through: :user_roles

  has_many :artist_users
  has_many :artists, through: :artist_users

  has_many :event_user_statuses
  has_many :events, through: :event_user_statuses

  has_many :venue_users
  has_many :venues, through: :venue_users

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :venue_users
  has_many :users, through: :venue_users
  has_many :events
end

app/models/venue_role.rb
class VenueRole < ActiveRecord::Base
  has_many :venue_users
end

app/models/venue_user.rb
class VenueUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue
end

app/controllers/event_user_statuses_controller.rb
class EventUserStatusesController < ApplicationController
  before_action :set_event_user_status, only: [:show, :edit, :update, :destroy]

  # GET /event_user_statuses
  # GET /event_user_statuses.json
  def index
    @event_user_statuses = EventUserStatus.all
  end

  # GET /event_user_statuses/1
  # GET /event_user_statuses/1.json
  def show
    @event_user_status = EventUserStatus.find(params[:id])
  end

  # GET /event_user_statuses/new
  def new
    @event_user_status = EventUserStatus.new
  end

  # GET /event_user_statuses/1/edit
  def edit
  end

  # POST /event_user_statuses
  # POST /event_user_statuses.json
  def create
    @event_user_status = EventUserStatus.new(event_user_status_params)

    respond_to do |format|
      if @event_user_status.save
        format.html { redirect_to @event_user_status, notice: 'Event user status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event_user_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @event_user_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_user_statuses/1
  # PATCH/PUT /event_user_statuses/1.json
  def update
    respond_to do |format|
      if @event_user_status.update(event_user_status_params)
        format.html { redirect_to @event_user_status, notice: 'Event user status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event_user_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_user_statuses/1
  # DELETE /event_user_statuses/1.json
  def destroy
    @event_user_status.destroy
    respond_to do |format|
      format.html { redirect_to event_user_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_user_status
      @event_user_status = EventUserStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_user_status_params
      params[:event_user_status].permit(:status, :user_id, :event_id)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/event_user_statuses_helper.rb
module EventUserStatusesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_user_statuses/_form.html.erb
<%= form_for(@event_user_status) do |f| %>
  <% if @event_user_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_user_status.errors.count, "error") %> prohibited this event_user_status from being saved:</h2>

      <ul>
      <% @event_user_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_user_statuses/edit.html.erb
<h1>Editing event_user_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_user_status %> |
<%= link_to 'Back', event_user_statuses_path %>

app/views/event_user_statuses/index.html.erb
<h1>Listing event_user_statuses</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @event_user_statuses.each do |event_user_status| %>
      <tr>
        <td><%= link_to 'Show', event_user_status %></td>
        <td><%= link_to 'Edit', edit_event_user_status_path(event_user_status) %></td>
        <td><%= link_to 'Destroy', event_user_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event user status', new_event_user_status_path %>

app/views/event_user_statuses/new.html.erb
<h1>New event_user_status</h1>

<%= render 'form' %>

<%= link_to 'Back', event_user_statuses_path %>

app/views/event_user_statuses/show.html.erb
<%= link_to 'Edit', edit_event_user_status_path(@event_user_status) %> |
<%= link_to 'Back', event_user_statuses_path %>