config/routes.rb
SoulControlBack::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :areas

  resources :countries

  resources :locations

  resources :venue_roles

  resources :venue_users

  resources :venues

  resources :statuses

  resources :tours

  resources :events

  resources :event_user_statuses

  resources :artists

  resources :roles

  resources :users

  resources :companies

  get "soulcontrol" => "soulcontrol#index"

  devise_scope :user do

    authenticated :user do
      root 'soulcontrol#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

  end

  

end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :artist_users
  has_many :users, through: :artist_users
  has_many :events
end

app/models/artist_user.rb
class ArtistUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :artist
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :locations
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_user_statuses
  has_many :users, through: :event_user_statuses
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :companies
  has_many :venues
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles
  has_many :users, through: :user_roles
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :events
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :user_roles
  has_many :roles, through: :user_roles

  has_many :artist_users
  has_many :artists, through: :artist_users

  has_many :event_user_statuses
  has_many :events, through: :event_user_statuses

  has_many :venue_users
  has_many :venues, through: :venue_users

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :venue_users
  has_many :users, through: :venue_users
  has_many :events
end

app/models/venue_role.rb
class VenueRole < ActiveRecord::Base
  has_many :venue_users
end

app/models/venue_user.rb
class VenueUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue
end

app/controllers/venue_roles_controller.rb
class VenueRolesController < ApplicationController
  before_action :set_venue_role, only: [:show, :edit, :update, :destroy]

  # GET /venue_roles
  # GET /venue_roles.json
  def index
    @venue_roles = VenueRole.all
  end

  # GET /venue_roles/1
  # GET /venue_roles/1.json
  def show
    @venue_role =  VenueRole.find(params[:id])
  end

  # GET /venue_roles/new
  def new
    @venue_role = VenueRole.new
  end

  # GET /venue_roles/1/edit
  def edit
  end

  # POST /venue_roles
  # POST /venue_roles.json
  def create
    @venue_role = VenueRole.new(venue_role_params)

    respond_to do |format|
      if @venue_role.save
        format.html { redirect_to @venue_role, notice: 'Venue role was successfully created.' }
        format.json { render action: 'show', status: :created, location: @venue_role }
      else
        format.html { render action: 'new' }
        format.json { render json: @venue_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venue_roles/1
  # PATCH/PUT /venue_roles/1.json
  def update
    respond_to do |format|
      if @venue_role.update(venue_role_params)
        format.html { redirect_to @venue_role, notice: 'Venue role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @venue_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venue_roles/1
  # DELETE /venue_roles/1.json
  def destroy
    @venue_role.destroy
    respond_to do |format|
      format.html { redirect_to venue_roles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue_role
      @venue_role = VenueRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_role_params
      params[:venue_role].permit(:name)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venue_roles_helper.rb
module VenueRolesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venue_roles/_form.html.erb
<%= form_for(@venue_role) do |f| %>
  <% if @venue_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue_role.errors.count, "error") %> prohibited this venue_role from being saved:</h2>

      <ul>
      <% @venue_role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venue_roles/edit.html.erb
<h1>Editing venue_role</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue_role %> |
<%= link_to 'Back', venue_roles_path %>

app/views/venue_roles/index.html.erb
<h1>Listing venue_roles</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @venue_roles.each do |venue_role| %>
      <tr>
        <td><%= link_to 'Show', venue_role %></td>
        <td><%= link_to 'Edit', edit_venue_role_path(venue_role) %></td>
        <td><%= link_to 'Destroy', venue_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue role', new_venue_role_path %>

app/views/venue_roles/new.html.erb
<h1>New venue_role</h1>

<%= render 'form' %>

<%= link_to 'Back', venue_roles_path %>

app/views/venue_roles/show.html.erb
<%= link_to 'Edit', edit_venue_role_path(@venue_role) %> |
<%= link_to 'Back', venue_roles_path %>